window.SLIDES = [
    "@https://tonycheal.com/",
    "slides/ICL OPD.jpg",
    "@https://binarydinosaurs.co.uk/Museum/icl/opdcompiler.php",
    "@https://en.wikipedia.org/wiki/Acorn_Archimedes",
    "slides/AandBEuclid.jpeg",
    "@https://www.computinghistory.org.uk/det/75967/Risc-OS-EUCLID-User-Guide/",
    "@https://www.computinghistory.org.uk/det/51984/ARCLIGHT/",
    "@https://web.archive.org/web/19961221034257/http://www.oakltd.demon.co.uk/",
    "slides/AutoCAD.png",
    "@https://rarehistoricalphotos.com/life-before-autocad-1950-1980/",
    "slides/LDCAPI1.jpeg",
    "slides/LDCAPI2.jpeg",
    "slides/RealAdjustableSetSquare.jpeg",
    "slides/QCAD.png",
    "@https://en.wikipedia.org/wiki/Apollonius_of_Perga",
    "@https://www.cut-the-knot.org/pythagoras/Apollonius.shtml",
    "@https://en.wikipedia.org/wiki/Problem_of_Apollonius#Ten_combinations_of_points,_circles,_and_lines",
    "@https://apollonius.design/",
    "@slides/final.html",
    // spares if required....
    "slides/Piston.png",
    "slides/PilotBoat.png",
    "slides/Euclid21990.jpg",
    "slides/ApoToolSprites.png",
    "slides/PilotBoatDebug.png",
    "@https://www.computinghistory.org.uk/det/816/Personal-Computer-World-November-1988/",
    "@slides/AcornNews_PCShowNewsletter89.pdf",
    "slides/AdjustableSetSquare.jpg",
    "@slides/APP155 (1st ed) - (1988)-opt.pdf",
    "slides/MiniMap.png",
    "slides/QCAD.png",
    "slides/AutoCAD.png",
    "slides/ArchimedesLive.png",
];
