window.SLIDES = [
    "@https://rarehistoricalphotos.com/life-before-autocad-1950-1980/",
    "slides/ApoManualCover.png",
    "slides/ApoToolSprites.png",
    "slides/PilotBoatDebug.png",
    "slides/AandBEuclid.jpeg",
    "@https://www.computinghistory.org.uk/det/816/Personal-Computer-World-November-1988/",
    "@slides/AcornNews_PCShowNewsletter89.pdf",
    "slides/AdjustableSetSquare.jpg",
    "@slides/APP155 (1st ed) - (1988)-opt.pdf",
    "slides/MiniMap.png",
    "slides/PilotBoat.png",
    "slides/Piston.png",
    "slides/QCAD.png",
    "slides/AutoCAD.png",
];
